name: Windows ARM64 CI experiment

on:
  workflow_dispatch:
  push:
    branches:
      - '3.14.before'
  pull_request:
    branches:
      - '3.14.before'

permissions:
  contents: read

jobs:
  build-windows:
    name: Windows ARM64
    uses: ./.github/workflows/reusable-windows.yml
    with:
      arch: arm64
      free-threading: false
